package it.heptartle.kbgg.domain.geekdo

data class GeekItem(val item: GeekItemData)

data class GeekItemData(val itemid: Int,
                        val objecttype: String,
                        val objectid: Int,
                        val label: String,
                        val labelpl: String,
                        val href: String,
                        val subtype: String,
                        val subtypes: List<String>,
                        val versioninfo: VersionInfo,
                        val name: String,
                        val alternatename: String,
                        val yearpublished: String,
                        val minplayers: String,
                        val maxplayers: String,
                        val minplaytime: String,
                        val maxplaytime: String,
                        val minage: String,
                        val override_rankable: Int,
                        val targetco_url: String,
                        val walmart_id: String,
                        val instructional_videoid: String,
                        val summary_videoid186475: String,
                        val playthrough_videoid: String,
                        val focus_videoid: String,
                        val bggstore_product: String,
                        val links: Links,
                        val linkcounts: LinkCounts,
                        val secondarynamescount: Int,
                        val alternatenamescount: Int,
                        val primaryname: Name,
                        val alternatenames: List<Name>,
                        val description: String,
                        val wiki: String,
                        val website: Website,
                        val imageid: String,
                        val images: RecommendationImages,
                        val imagepagehref: String,
                        val imageurl: String,
                        val topimageurl: String,
                        val itemstate: String,
                        val special_user: SpecialUser)

data class VersionInfo(val kickstarter_widget_url: String,
                       val gamepageorderurl: String,
                       val shopifyitem: String)

data class Links(val boardgamedesigner: List<LinkInfo>,
                 val boardgameartist: List<LinkInfo>,
                 val boardgamepublisher: List<LinkInfo>,
                 val boardgamehonor: List<LinkInfo>,
                 val boardgamecategory: List<LinkInfo>,
                 val boardgamemechanic: List<LinkInfo>,
                 val boardgameexpansion: List<LinkInfo>,
                 val boardgameversion: List<LinkInfo>,
                 val expandsboardgame: List<LinkInfo>,
                 val boardgameintegration: List<LinkInfo>,
                 val contains: List<LinkInfo>,
                 val containedin: List<LinkInfo>,
                 val reimplementation: List<LinkInfo>,
                 val reimplements: List<LinkInfo>,
                 val boardgamefamily: List<LinkInfo>,
                 val videogamebg: List<LinkInfo>,
                 val boardgamesubdomain: List<LinkInfo>,
                 val boardgameaccessory: List<LinkInfo>,
                 val commerceweblink: List<LinkInfo>)

data class LinkInfo(val name: String,
                    val objecttype: String,
                    val objectid: String,
                    val primarylink: Int,
                    val itemstate: String,
                    val href: String)

data class LinkCounts(val boardgamedesigner: Int,
                      val boardgameartist: Int,
                      val boardgamepublisher: Int,
                      val boardgamehonor: Int,
                      val boardgamecategory: Int,
                      val boardgamemechanic: Int,
                      val boardgameexpansion: Int,
                      val boardgameversion: Int,
                      val expandsboardgame: Int,
                      val boardgameintegration: Int,
                      val contains: Int,
                      val containedin: Int,
                      val reimplementation: Int,
                      val reimplements: Int,
                      val boardgamefamily: Int,
                      val videogamebg: Int,
                      val boardgamesubdomain: Int,
                      val boardgameaccessory: Int,
                      val commerceweblink: Int)

data class Website(val url: String,
                   val title: String)

data class SpecialUser(val username: String,
                       val userid: String)